POST /secret/generate_key HTTP/1.1
Host: 127.0.0.1:5000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcyNTI5MDgwOH0.nrgeBtSPTFkNjrXIo34IS6KUr3hBaWEtdZgAKS3kaaQ
